global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 5s
    honor_labels: true

  - job_name: 'turbine-rul-pipeline'
    static_configs:
      - targets: ['turbine-rul:8080']  # If you add a metrics endpoint later
    scrape_interval: 10s

rule_files:
  - "alert_rules.yml"

