artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/train.csv           
  train_preprocessed_path: artifacts/data_transformation/train_preprocessed.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl

feature_engineering:
  root_dir: artifacts/feature_engineering
  train_preprocessed_path: artifacts/data_transformation/train_preprocessed.csv
  engineered_features_path: artifacts/feature_engineering/train_features.csv
  long_term_pipeline_path: artifacts/feature_engineering/long_term_pipeline.pkl
  short_term_pipeline_path: artifacts/feature_engineering/short_term_pipeline.pkl

database:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres