artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv

drift_detection:
  root_dir: artifacts/drift_detection
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  reference_data_path: artifacts/drift_detection/reference_data.pkl
  reference_stats_path: artifacts/drift_detection/reference_stats.pkl
  drift_report_path: artifacts/drift_detection/drift_report.json

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/train.csv           
  train_preprocessed_path: artifacts/data_transformation/train_preprocessed.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl

feature_engineering:
  root_dir: artifacts/feature_engineering
  train_preprocessed_path: artifacts/data_transformation/train_preprocessed.csv
  engineered_features_path: artifacts/feature_engineering/train_features.csv
  long_term_pipeline_path: artifacts/feature_engineering/long_term_pipeline.pkl
  short_term_pipeline_path: artifacts/feature_engineering/short_term_pipeline.pkl

model_training:
  root_dir: artifacts/model_training
  engineered_features_path: artifacts/feature_engineering/train_features.csv
  model_path: artifacts/model_training/ngboost_model.pkl
  selected_features_path: artifacts/model_training/selected_features.pkl
  feature_importance_path: artifacts/model_training/feature_importance.csv
  cv_results_path: artifacts/model_training/cv_results.csv
  metrics_path: artifacts/model_training/metrics.csv

model_prediction:
  root_dir: artifacts/model_prediction
  test_data_path: artifacts/data_ingestion/test.csv  # Raw test data with RUL
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  long_term_pipeline_path: artifacts/feature_engineering/long_term_pipeline.pkl
  short_term_pipeline_path: artifacts/feature_engineering/short_term_pipeline.pkl
  model_path: artifacts/model_training/ngboost_model.pkl
  selected_features_path: artifacts/model_training/selected_features.pkl
  # Output paths
  predictions_path: artifacts/model_prediction/predictions.csv
  evaluation_rul_path: artifacts/model_prediction/true_rul.csv
  evaluation_metrics_path: artifacts/model_prediction/evaluation_metrics.csv
  evaluation_plots_path: artifacts/model_prediction/evaluation_plots.png


#Updated version

database:
  host: 192.168.1.41
  port: 5432
  database: postgres
  username: postgres
  password: postgres